import { useState } from "react"
import ModalShell from "../ui/ModalShell"

export interface TwoFactorSetupModalProps {
  open: boolean
  onClose: () => void
}

type Step = "intro" | "verify" | "recovery"

export default function TwoFactorSetupModal({
  open,
  onClose,
}: TwoFactorSetupModalProps) {
  // ✅ Hooks must be unconditional
  const [step, setStep] = useState<Step>("intro")
  const [otp, setOtp] = useState("")
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Example QR secret (backend-generated in real flow)
  const qrCodeUrl =
    "https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=otpauth://totp/PragatiAI?secret=ABC123"

  // Example recovery codes
  const recoveryCodes = [
    "A1B2-C3D4",
    "E5F6-G7H8",
    "I9J0-K1L2",
  ]

  // ✅ Conditional render AFTER hooks
  if (!open) return null

  const handleVerify = async () => {
    setError(null)

    if (otp.length !== 6) {
      setError("Enter the 6-digit code from your authenticator.")
      return
    }

    try {
      setLoading(true)

      // 🔗 READY FOR BACKEND
      // await apiClient.post("/security/2fa/verify", { otp })

      console.log("2FA verified:", otp)

      setStep("recovery")
    } catch {
      setError("Invalid code. Please try again.")
    } finally {
      setLoading(false)
    }
  }

  const handleFinish = () => {
    // 🔗 READY FOR BACKEND
    // await apiClient.post("/security/2fa/enable")

    console.log("2FA enabled")
    onClose()
  }

  return (
    <ModalShell title="Two-Factor Authentication" onClose={onClose}>
      <div className="space-y-5 text-sm">
        {/* STEP 1: Intro / QR */}
        {step === "intro" && (
          <>
            <p className="text-slate-600">
              Scan the QR code below using an authenticator app
              (Google Authenticator, Authy, etc.).
            </p>

            <div className="flex justify-center">
              <img
                src={qrCodeUrl}
                alt="2FA QR Code"
                className="h-44 w-44 border rounded"
              />
            </div>

            <div className="flex justify-end">
              <button
                type="button"
                onClick={() => setStep("verify")}
                className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-800"
              >
                I’ve scanned the code
              </button>
            </div>
          </>
        )}

        {/* STEP 2: Verify OTP */}
        {step === "verify" && (
          <>
            <p className="text-slate-600">
              Enter the 6-digit code generated by your
              authenticator app.
            </p>

            <input
              type="text"
              value={otp}
              onChange={(e) =>
                setOtp(e.target.value.replace(/\D/g, ""))
              }
              maxLength={6}
              className="w-full text-center tracking-widest rounded-lg border border-slate-300 px-3 py-2 text-lg focus:outline-none focus:ring-2 focus:ring-slate-900/20"
              placeholder="123456"
            />

            {error && (
              <p className="text-sm text-red-600">
                {error}
              </p>
            )}

            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={() => setStep("intro")}
                className="text-sm text-slate-600 hover:text-slate-900"
              >
                Back
              </button>

              <button
                type="button"
                onClick={handleVerify}
                disabled={loading}
                className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-800 disabled:opacity-60"
              >
                {loading ? "Verifying..." : "Verify"}
              </button>
            </div>
          </>
        )}

        {/* STEP 3: Recovery Codes */}
        {step === "recovery" && (
          <>
            <p className="text-slate-600">
              Save these recovery codes in a safe place.
              Each code can be used once if you lose access
              to your authenticator.
            </p>

            <div className="grid grid-cols-1 gap-2 rounded-lg border border-slate-200 p-3 font-mono text-sm">
              {recoveryCodes.map((code) => (
                <span key={code}>{code}</span>
              ))}
            </div>

            <div className="flex justify-end">
              <button
                type="button"
                onClick={handleFinish}
                className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-black hover:bg-green-700"
              >
                Finish setup
              </button>
            </div>
          </>
        )}
      </div>
    </ModalShell>
  )
}
